version: '3.10'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER: airflowuser
      POSTGRES_DB: airflowdb
      AIRFLOW_SCHEMA: airflow
    expose:
      - "5432"
    restart: always
    volumes:
      - ./scripts_postgres:/docker-entrypoint-initdb.d

  postgres-dbt:
    image: postgres
    environment:
      POSTGRES_PASSWORD: pssd
      POSTGRES_USER: dbtuser
      POSTGRES_DB: dbtdb
      DBT_SCHEMA: dbt
      DBT_RAW_DATA_SCHEMA: dbt_raw_data
    expose:
      - "5432"
    restart: always
    volumes:
      - ./sample_data:/sample_data

  airflow:
    build: .
    # entrypoint: "airflow webserver && airflow scheduler"  # Specify the entrypoint command
    restart: always
    environment:
      DBT_PROFILES_DIR: /dbt
      AIRFLOW_HOME: /airflow
      AIRFLOW__CORE__DAGS_FOLDER: /airflow/dags
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__DAG_CONCURRENCY: 4
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4
      POSTGRES_USER: airflowuser
      POSTGRES_PASSWORD: pssd
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: airflowdb
      DBT_POSTGRES_PASSWORD: pssd
      DBT_POSTGRES_USER: dbtuser
      DBT_POSTGRES_DB: dbtdb
      DBT_DBT_SCHEMA: dbt
      DBT_DBT_RAW_DATA_SCHEMA: dbt_raw_data
      DBT_POSTGRES_HOST: postgres-dbt
    depends_on:
      - postgres
      - postgres-dbt
    ports:
      - "8080:8080"
    volumes:
      - ./dbt:/dbt
      - ./airflow:/airflow
      - ./python:/python
      - ./datafiles:/datafiles

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    depends_on:
      - postgres
      - postgres-dbt
