version: "2"
x-redash-service: &redash-service
  image: redash/redash:8.0.0.b32245
  depends_on:
    - postgres-dbt
    - redis
  env_file: .env
  restart: always

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: redis:5.0-alpine
    restart: always
    ports:
      - '6379:6379'

  postgres-dbt:
    image: postgres:9.6-alpine
    env_file:
      - .env
    expose:
      - "5433"
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - ./sample_data:/sample_data

  airflow:
    build: .
    # entrypoint: "airflow webserver && airflow scheduler"  # Specify the entrypoint command
    restart: always
    environment:
      DBT_PROFILES_DIR: /dbt
      AIRFLOW_HOME: /airflow
      AIRFLOW__CORE__DAGS_FOLDER: /airflow/dags
      AIRFLOW__CORE__PARALLELISM: 4
      AIRFLOW__CORE__DAG_CONCURRENCY: 4
      AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: 4
      POSTGRES_USER: dbtuser
      POSTGRES_PASSWORD: pssd
      POSTGRES_HOST: postgres-dbt
      POSTGRES_PORT: 5432
      POSTGRES_DB: dbtdb
      DBT_POSTGRES_PASSWORD: pssd
      DBT_POSTGRES_USER: dbtuser
      DBT_POSTGRES_DB: dbtdb
      DBT_DBT_SCHEMA: dbt
      DBT_DBT_RAW_DATA_SCHEMA: dbt_raw_data
      DBT_POSTGRES_HOST: postgres-dbt
    depends_on:
      - postgres-dbt
    ports:
      - "8080:8080"
    volumes:
      - ./dbt:/dbt
      - ./airflow:/airflow
      - ./python:/python
      - ./datafiles:/datafiles
      # - C:/Users/Hp/.dbt:/root/.dbt

